### ISSUE TITLE
Not published to maven central using scala 2.12

### ISSUE THREAD

**Issue by Jaystified** [scala-js/scala-js-env-jsdom-nodejs#5]
Only the 2.10 version seems to have been published to maven central.
Please publish the version compiled with scala 2.12

**Comment by sjrd** [comment]
That does not seem to be accurate. [It is published on Maven Central for 2.12](http://search.maven.org/#search%7Cga%7C1%7Cscalajs-env-jsdom-nodejs).

Note that this repo is only useful if you are using Scala.js 1.x, as indicated in the readme. If you are using Scala.js 0.6.x, you should not even try to add a dependency on scalajs-env-jsdom-nodejs.
