### ISSUE TITLE
Configurable `jsdom` directory in `JSDOMNodeJSEnv.Config`

### ISSUE THREAD

**Issue by ptrdom** [scala-js/scala-js-env-jsdom-nodejs#53]
Would a PR to add this setting be accepted? Seems like it would definitely be useful and I cannot think of a simple workaround for it, scalajs-bundler even has its own copy of `JSDOMNodeJSEnv` to do it - https://github.com/scalacenter/scalajs-bundler/blob/main/sbt-scalajs-bundler/src/main/scala/scalajsbundler/JSDOMNodeJSEnv.scala.

**Comment by gzm0** [comment]
Isn't it enough to set the `NODE_PATH` env variable for this?

https://stackoverflow.com/a/26293141/1149944

**Comment by ptrdom** [comment]
@gzm0 This indeed works, env variables are configurable in the current `Config` implementation. Thank you!
